matrix:
        include:
                - language: java
                  jdk: oraclejdk8
                  before_script: cd prototype/backend
                  script: mvn clean verify

                - language: android
                  sudo: false
                  jdk: oraclejdk8
                  android:
                        components:
                                - tools
                                - platform-tools
                                - android-26
                                - build-tools-26.0.2
                                - extra-google-google_play_services
                                - extra-google-m2repository
                                - extra-android-m2repository
                                - addon-google_apis-google-26
                                - sys-img-armeabi-v7a-android-26
                  before_script:
                        - cd prototype/android
                        - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a --tag google_apis
                        - emulator -avd test -no-skin -no-audio -no-window &
                        - android-wait-for-emulator
                        - adb shell input keyevent 82 &
                  script: gradle build connectedCheck

notifications:
        slack: oose-group19:ryaOZ0MyxhojlMt6WavN3giX
