matrix:
        include:
                - language: java
                  jdk: oraclejdk8
                  before_script: cd prototype/backend
                  script: mvn clean verify

                - language: android
                  sudo: false
                  jdk: oraclejdk8
                  android: 
                        components:
                                - tools
                                - android-26
                                - build-tools-26.0.2
                                - tools  
                                - extra-google-google_play_services
                                - extra-google-m2repository
                                - extra-android-m2repository
                                - addon-google_apis-google-19
                  before_script: 
                        - cd prototype/android
                  script: gradle build connectedCheck

notifications:
        slack: oose-group19:ryaOZ0MyxhojlMt6WavN3giX

